export interface Emoji
{
  name : string;
  emoji : string;
};

export const fruits = [
    { name: 'banana', emoji: '🍌' },
    { name: 'apple', emoji: '🍎' },
    { name: 'grape', emoji: '🍇' },
    { name: 'lemon', emoji: '🍋' },
    { name: 'orange', emoji: '🍊' },
    { name: 'pear', emoji: '🍐' },
    { name: 'watermelon', emoji: '🍉' },
    { name: 'cherry', emoji: '🍒' },
    { name: 'pineapple', emoji: '🍍' },
    { name: 'peach', emoji: '🍑' },
    { name: 'strawberry', emoji: '🍓' },
    { name: 'mango', emoji: '🥭' },
    { name: 'kiwi', emoji: '🥝' },
    { name: 'coconut', emoji: '🥥' },
    { name: 'apricot', emoji: '🍑' },
    { name: 'blueberry', emoji: '🫐' },
    { name: 'plum', emoji: '🍑' },
    { name: 'fig', emoji: '🍈' },
    { name: 'pomegranate', emoji: '🍊' },
    { name: 'dragonfruit', emoji: '🍍' },
    { name: 'pear', emoji: '🍐' },
    { name: 'raspberry', emoji: '🍇' },
    { name: 'blackberry', emoji: '🍇' },
    { name: 'cantaloupe', emoji: '🍈' },
    { name: 'papaya', emoji: '🍈' },
    { name: 'lime', emoji: '🍋' },
    { name: 'nectarine', emoji: '🍑' },
    { name: 'tangerine', emoji: '🍊' },
    { name: 'clementine', emoji: '🍊' },
    { name: 'starfruit', emoji: '🍍' },
    { name: 'lychee', emoji: '🍇' },
    { name: 'melon', emoji: '🍈' },
    { name: 'jackfruit', emoji: '🍈' },
    { name: 'grapefruit', emoji: '🍊' },
    { name: 'apricot', emoji: '🍑' },
    { name: 'date', emoji: '🍇' }
  ];

 export const  animals = [
    { name: '9erd', emoji: '🐒' },
    { name: 'kelb', emoji: '🐶' },
    { name: 'dib', emoji: '🐺' },
    { name: 'mesh', emoji: '🐱' },
    { name: 'nmer', emoji: '🐅' },
    { name: 'fa8d', emoji: '🐆' },
    { name: '3awd', emoji: '🐎' },
    { name: 'tour', emoji: '🐂' },
    { name: 'begra', emoji: '🐄' },
    { name: '7ellouf', emoji: '🐷' },
    { name: 'khenzir', emoji: '🐗' },
    { name: '7awli', emoji: '🐏' },
    { name: 'khrof', emoji: '🐑' },
    { name: 'me3za', emoji: '🐐' },
    { name: 'jmel', emoji: '🐪' },
    { name: 'fil', emoji: '🐘' },
    { name: 'far', emoji: '🐭' },
    { name: 'Tobba', emoji: '🐀' },
    { name: '9nia', emoji: '🐰' },
    { name: 'doub', emoji: '🐻' },
    { name: 'kowala', emoji: '🐨' },
    { name: 'panda', emoji: '🐼' },
    { name: 'djaja', emoji: '🐓' },
    { name: 'fellous', emoji: '🐥' },
    { name: 'bTri9', emoji: '🐧' },
    { name: 'jrana', emoji: '🐸' },
    { name: 'timsa7', emoji: '🐊' },
    { name: 'fekroun', emoji: '🐢' },
    { name: '7ensh', emoji: '🐍' },
    { name: 'tinnin', emoji: '🐉' },
    { name: 'labalen', emoji: '🐳' },
    { name: 'dlfine', emoji: '🐬' },
    { name: '7outa', emoji: '🐟' },
    { name: 'RoTala', emoji: '🐙' },
    { name: 'kokiaj', emoji: '🐚' },
    { name: 'boubbousha', emoji: '🐌' },
    { name: 'douda', emoji: '🐛' },
    { name: 'nemla', emoji: '🐜' },
    { name: 'ne7la', emoji: '🐝' },
    { name: 'koksinil', emoji: '🐞' }
  ];

